"""Execution endpoints: submit a portfolio execution, fetch its status/report."""
import uuid
from typing import Annotated

from fastapi import APIRouter, Depends, Header, Request, Response, status
from sqlalchemy.ext.asyncio import AsyncSession

from src.core.auth import CurrentUser
from src.core.database import get_db
from src.schemas.execution import ExecutionCreate, ExecutionEventReport, ExecutionReport
from src.service.execution import ExecutionService

router = APIRouter()


def get_execution_service(session: AsyncSession = Depends(get_db)) -> ExecutionService:
    return ExecutionService(session)


@router.post("", status_code=status.HTTP_202_ACCEPTED, response_model=ExecutionReport)
async def submit_execution(
    body: ExecutionCreate,
    user_id: CurrentUser,
    request: Request,
    response: Response,
    idempotency_key: Annotated[str, Header(min_length=8, max_length=255, description=(
        "One key per execution intent, generated by the client (e.g. a UUID). Resending the same "
        "key with the same body returns, or resumes, the same execution instead of trading again."))],
    service: ExecutionService = Depends(get_execution_service),
) -> ExecutionReport:
    """Accepts BUY / SELL / REBALANCE instructions and executes them in the background.

    Poll `GET /executions/{id}` for progress; the final report is also delivered through the notification outbox.
    """
    execution, replayed = await service.submit(user_id, idempotency_key, body)
    response.headers["Location"] = str(request.url_for("get_execution", execution_id=execution.id))
    if replayed:
        response.headers["Idempotent-Replayed"] = "true"
    return ExecutionReport.model_validate(execution)


@router.get("/{execution_id}", response_model=ExecutionReport)
async def get_execution(
    execution_id: uuid.UUID, user_id: CurrentUser, service: ExecutionService = Depends(get_execution_service),
) -> ExecutionReport:
    return ExecutionReport.model_validate(await service.get(user_id, execution_id))


@router.get("/{execution_id}/events", response_model=list[ExecutionEventReport])
async def list_execution_events(
    execution_id: uuid.UUID, user_id: CurrentUser, service: ExecutionService = Depends(get_execution_service),
) -> list[ExecutionEventReport]:
    """Audit trail: every state change of the execution and its orders, oldest first."""
    return [ExecutionEventReport.model_validate(e) for e in await service.list_events(user_id, execution_id)]
